config/routes.rb
class UrlsRoutingConstraint
  def self.matches?(request)
    Url.find_by_short(request.path_parameters[:short]).present?
  end
end

Rails.application.routes.draw do
  resources :urls, param: :short
  resources :usages, only: [:index]

  root 'urls#index'

  get '*short', to: 'urls#show', constraints: UrlsRoutingConstraint, as: :short
end

app/models/url.rb
class Url < ActiveRecord::Base
  include ActiveModel::Validations

  has_many :usages

  validates_presence_of :regular, :short
  validates_uniqueness_of :regular, :short
  validates :regular, uniqueness: true, url: true

  before_validation do
    if short.blank?
      loop do
        code = SecureRandom.hex(3)
        if self.class.find_by_short(code).blank?
          self.short = code
          break
        end
      end
    end
  end

  def to_param
    short
  end

  def to_s
    regular
  end
end

app/models/usage.rb
class Usage < ActiveRecord::Base
  belongs_to :url, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  respond_to :html, :json

  before_filter :find_url, except: [:index, :new, :create]

  def index
    @urls = Url.all
    @old_urls = Url.where('created_at < ?', 14.days.ago.end_of_day)
    @page_title = 'URLs List'

    Url.where('created_at < ?', 15.days.ago.end_of_day).destroy_all
  end

  def show
    if @url.present?
      Usage.create(url: @url, who: request.remote_ip)
      redirect_to @url.regular
    else
      flash[:danger] = 'Could not find URL'
      redirect_to root_path
    end
  end

  def new
    @url = Url.new
    @page_title = 'New URL'
  end

  def create
    @url = Url.create(url_params)

    respond_with @url do |format|
      format.html do
        if @url.valid? && @url.persisted?
          flash[:success] = 'Successfully added new URL'
          redirect_to root_path
        else
          @page_title = 'New URL'
          flash.now[:danger] = 'Unable to add new URL'
          render :new
        end
      end
    end
  end

  def edit
    @page_title = 'Edit URL'
  end

  def update
    if @url.update_attributes(url_params)
      flash[:success] = 'Successfully updated URL'
      redirect_to root_path
    else
      @page_title = 'Edit URL'
      flash.now[:danger] = 'Unable to update URL'
      render :edit
    end
  end

  def destroy
    if @url.destroy
      flash[:success] = 'Successfully removed URL'
    else
      flash[:danger] = 'Unable to remove URL'
    end

    redirect_to root_path
  end

  private

  def find_url
    @url = Url.find_by_short(params[:short])
  end

  def url_params
    params.require(:url).permit(:regular, :short)
  end
end

app/controllers/usages_controller.rb
class UsagesController < ApplicationController
  def index
    @usages = Usage.order('created_at DESC').all
    @page_title = 'Logs'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title UrlShortener

    = javascript_include_tag 'application'
    = stylesheet_link_tag    'application', media: 'all'
    = csrf_meta_tags

  %body
    .container-fluid
      .row.main-container
        .col-md-12
          - flash.each do |name, msg|
            %div{class: "alert alert-row alert-dismissible alert-#{name}"}
              %button.close{'data-dismiss' => 'alert', :type => 'button'}
                %span{'aria-hidden' => 'true'} ×
                %span.sr-only Close
              = msg

          = link_to 'Home', root_path
          &bull;
          = link_to 'Logs', usages_path

          = yield

app/views/urls/_form.html.haml
.row
  .col-sm-8.col-sm-offset-2
    = simple_form_for @url, html: { class: 'form-horizontal'}, wrapper: :horizontal_form do |f|
      = f.error_notification

      = f.input :regular, label: 'Regular URL'
      - if f.object.persisted?
        = f.input :short, label: 'Short URL slug'

      .text-right
        = f.submit 'Save', class: 'btn btn-primary'

app/views/urls/_url.html.haml
%tr
  %td= link_to url, url.regular, target: '_blank'
  %td= link_to short_url(url.short), short_url(url.short), target: '_blank'
  %td= url.usages_count
  %td
    = link_to 'Edit', edit_url_path(url)
    &bull;
    = link_to 'Remove', url_path(url), method: :delete, data: { confirm: 'Are you sure you want to remove this URL?' }

app/views/urls/edit.html.haml
%h1= @page_title

= render partial: 'form'

app/views/urls/index.html.haml
%h1= @page_title

.row
  .col-sm-12
    - if @urls.present?
      %table.table
        %thead
          %th URL
          %th Short Url
          %th Used Times
          %th Actions
        %tbody
          = render @urls
    - else
      %p No URLs exist yet.

.row
  .col-sm-12
    = link_to 'Add new URL', new_url_path, class: 'btn btn-primary'

- if @old_urls.present?
  .row
    .col-sm-12
      %h2 URLs that are going to be removed tomorrow
      %thead
        %th URL
        %th Short Url
        %th Used Times
        %th Actions
      %tbody
        = render @urls

app/views/urls/new.html.haml
%h1= @page_title

= render partial: 'form'

app/views/usages/_usage.html.haml
%tr
  %td= usage.created_at
  %td= usage.who
  %td= usage.url
  %td= short_url(usage.url.short)

app/views/usages/index.html.haml
%h1= @page_title

.row
  .col-sm-12
    - if @usages.present?
      %table.table
        %thead
          %th When
          %th Who
          %th Url
          %th Short URL
        %tbody
          = render @usages
    - else
      %p No logs exist yet.